name: slock
version: 0.1
vendor: Simon Jentzsch <simon.jentzsch@slock.it>
summary: the slock-service controlling the blockchain
description: the service checking for access to a device on the ethereum-blockchain.
icon: slock_icon.png
frameworks:
  - ethereum

parts:
   slock:
     plugin: nodejs 
     source: git://github.com/slockit/slock-js.git

     files-to-copy:
       plugin: copy
       files:
             bin/arm-node: bin/arm-node
             bin/nodebinwrapper.sh: slockjs_exec

services:
  slockjs:
    start : slockjs_exec
      caps:
      - ethereum_ipc