name: slock
version: 0.1
vendor: Simon Jentzsch <simon.jentzsch@slock.it>
summary: the slock-service controlling the blockchain
architectures: [amd64, armhf]
description: the service checking for access to a device on the ethereum-blockchain.
icon: slock_icon.png
frameworks:
  - ethereum
config: bin/configurator

parts:
  slock:
    plugin: nodejs
    source: git://github.com/slockit/slock-js.git

  files-to-copy:
    plugin: copy
    files:
      bin/arm-node: bin/arm-node
      bin/nodebinwrapper.sh: bin/slockjs_exec
      config/configurator.py: bin/configurator
      config/default_config.yaml: config/default_config.yaml

  configurator:
    plugin: python2
    python-packages:
      - PyYAML

services:
  slockjs:
    start: bin/slockjs_exec
    description: "The slock.it application"
    caps:
      - ethereum_ipc
      - network-client
      - network-service
      - network-admin