---
modules:
  debug: {}
  eth:
    client: /root/.ethereum/geth.ipc
    contracts:
      doorlock4:
        adr: '0xdf373f3dab2561668e239ca6e43a8c6aaeb3f825'
        close: 255
        command: 98
        gpio: 3
        nodeid: 4
        open: 0
        stopOnError: true
        useStorage: false
      switch:
        adr: '0xad5e5a5bc4654dbef0d5cabd7abeb426769c073a'
        gpio: 4
        nodeid: 5
        command: 37
        stopOnError: true
        useStorage: false
  websocket:
    host: slock.it
    port: 8080
  zway:
    host: 192.168.1.110
    port: 8083

